version: "3.9"

services:

  ################################################
  # API
  ################################################
  api:
    build: .
    container_name: talentflow-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules


  ################################################
  # PostgreSQL
  ################################################
  postgres:
    image: postgres:16-alpine
    container_name: talentflow-postgres
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  ################################################
  # Redis
  ################################################
  redis:
    image: redis:7-alpine
    container_name: talentflow-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data


  ################################################
  # Prometheus
  ################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: talentflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api


  ################################################
  # Grafana
  ################################################
  grafana:
    image: grafana/grafana:latest
    container_name: talentflow-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus


################################################
# Volumes
################################################
volumes:
  pgdata:
  redisdata:
  grafana-data:
